In [1]:
%pip install  opencv-python

   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
    --------------------------------------- 1.0/38.8 MB 30.7 MB/s eta 0:00:02
   - -------------------------------------- 1.5/38.8 MB 30.7 MB/s eta 0:00:02
   - -------------------------------------- 1.5/38.8 MB 30.7 MB/s eta 0:00:02
   - -------------------------------------- 1.5/38.8 MB 30.7 MB/s eta 0:00:02
   - -------------------------------------- 1.5/38.8 MB 30.7 MB/s eta 0:00:02
   - -------------------------------------- 1.5/38.8 MB 30.7 MB/s eta 0:00:02
   - -------------------------------------- 1.9/38.8 MB 6.0 MB/s eta 0:00:07
   -- ------------------------------------- 2.7/38.8 MB 7.8 MB/s eta 0:00:05
   -- ------------------------------------- 2.7/38.8 MB 7.8 MB/s eta 0:00:05
   -- ------------------------------------- 2.7/38.8 MB 7.8 MB/s eta 0:00:05
   -- ------------------------------------- 2.7/38.8 MB 7.8 MB/s eta 0:00:05
   -- ------------------------------------- 2.7/38.8 MB 7.8 MB/s eta 0:00:05



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


How To read Picture from  the user

In [2]:
import cv2
img=cv2.imread(''"Sachin pic.jpg",0) #There are three chhanel here for colour we can choose any one.
cv2.imshow('img',img)       #I wiil take two argument one is frame name and other is variable name which we have to look.
print(img)
cv2.waitKey(0)             #no off milli second the img have to show on the screen
cv2.destroyAllWindows

[[171 167 165 ... 186 187 187]
 [172 168 168 ... 187 188 188]
 [180 176 175 ... 188 189 188]
 ...
 [165 165 165 ... 169 169 171]
 [165 165 165 ... 169 170 171]
 [165 165 165 ... 169 171 171]]


<function destroyAllWindows>

How to read video from the web cam

In [1]:
import cv2
cap=cv2.VideoCapture(0)
while (True):
    ret,frame=cap.read()
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows

<function destroyAllWindows>

How to read gray scale video from the web cam

In [2]:
import cv2
cap=cv2.VideoCapture(0)
while(True):
    ret,frame=cap.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) #converting the frame into gray scale and it take two parameter

    cv2.imshow('Video',gray)
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
    

error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


How to save Video from the camera

In [ ]:
import cv2
cap = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*'XVID')  #Using a new class VideoWriter_fourcc() we can write the video in the file
out = cv2.VideoWriter('output.avi', fourcc, 20.0, (640, 480))

while True:
    ret, frame = cap.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) #converting the frame into gray scale and it take two parameter
    if ret:
        out.write(frame)            #It will write the video in the file
        cv2.imshow('frame', gray)               #It will show the gray the video in the gray colour
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break

cap.release()
out.release()
cv2.destroyAllWindows()  


How to draw a line and rectangle on image

In [ ]:
import numpy as np
import cv2
img=cv2.imread('test.jpg',0) #if we did't give second parameter then it will load default
print(img)
img=cv2.line(img,(0,0),(255,255),(255,0,0),4) #it will draw a line on image and it take four argumant (name of image,startig point,ending point,thickness)
img=cv2.arrowedLine(img,(155,0),(255,263),(255,0,0),4) #it will draw a line on image and it take four argumant (name of image,startig point,ending point,thickness) it will draw arrow line
img=cv2.rectangle(img,(384,0),(510,128),(0,0,255),1) #it will draw a rectangel last one is thickness if we use -1 it will fill the rectangle
font=cv2.FONT_HERSHEY_COMPLEX
#img=cv2.putText('img','opencv'(10,500),font,4,(255,255,255),10,cv2.LINE_AA)
cv2.imshow('frame',img)
cv2.waitKey()
cv2.destroyAllWindows

How to reset the frame size in Open cv

In [1]:
import cv2
cap=cv2.VideoCapture(0)
print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv2.CAP_PROP_FRAME_TYPE))
cap.set(3,1200)
cap.set(4,1200)
print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv2.CAP_PROP_FRAME_TYPE))
while True:
    ret,frame=cap.read()
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows
    

640.0
-1.0
1280.0
-1.0


error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1301: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'


How to Mark the date and time on the output screen

In [ ]:
import cv2
import datetime
cap=cv2.VideoCapture(0)
while True:
    ret,frame=cap.read()
    font=cv2.FONT_HERSHEY_SIMPLEX
    cv2.putText(frame,str(datetime.datetime.now()),(10,50),font,1,(256,255,255),2,cv2.LINE_AA)
    #the first value is frame and the date and time is in the integer converting it into the string
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break 
cap.release 
cv2.destroyAllWindows

We can also create some event by using diffrent button in the mouse,It will be called as the mouse event

How to create track bar by usin opencv and numpay array and the change the colour

In [ ]:
import cv2
import numpy as np

def trackbar_value (x): #This function will print the current location of the track bar
    print(x)
    
img = np.zeros((512, 512, 3), dtype = "uint8") #the first one specify the height and width of the pic and the third one specify the color channel
                                                #dtype specify the type of the no. of pixel in the image
                                                
cv2.namedWindow('image')              #creating a window for the new 

cv2.createTrackbar('B','image',0,255, trackbar_value)   
cv2.createTrackbar('G','image',0,255, trackbar_value)                                         
cv2.createTrackbar('R','image',0,255, trackbar_value)                                         

while(1):
    cv2.imshow('image',img)
    k=cv2.waitKey(1) & 0xFF 
    if k==27:
        break
    
    #It will print in the termnal the current location of the trackbar
    b=cv2.getTrackbarPos('B','image')
    g=cv2.getTrackbarPos('G','image')
    r=cv2.getTrackbarPos('R','image')

    img[:]=[b,g,r]
    
cv2.destroyAllWindows()

#we can also change the colou of any picture and print its value on the same picture

How to detect object by using VIOLA & JONES method

In [6]:
import cv2
cap=cv2.VideoCapture(0)
while (True):
    fail,actual_video=cap.read()
    bgr=cv2.cvtColor(actual_video,cv2.COLOR_BGR2Lab)
    cv2.imshow('actual_video',bgr)
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()


NameError: name 'datetime' is not defined